---
title: "Census Data 2020"
author: "Alan Jackson"
date: "2022-10-15"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidycensus)

census_api_key("c458095036ca1037f97b9c7019b6a7ac2dbf90d4")

local_crs <- 26915 # NAD83 UTM projection zone 15
google_crs <- 4326

knitr::opts_chunk$set(echo = TRUE)
```

##        What do I want to download?

```{r view}

Looky1 <- load_variables(2020, c("pl"), cache=TRUE)
Looky <- load_variables(2020, c("acs5"), cache=TRUE)

#     All these by block

dec_vars <- c(Pop="P1_001N", # total population
              Pop_white="P1_003N", # white
              Pop_black="P1_004N", # black
              Pop_asian="P1_006N", # Asian
              Pop_hispanic="P2_002N", # Hispanic
              Pop_not_hisp="P2_005N"  # White not Hispanic
              )

#####   ACS data is 5 year data from 2015-2020

#   All these by block group
acs_vars_b <- c(Pop_blk_grp="B01001_001", # Total population by blk grp
              Med_inc="B19013_001", # median household income, blk grp
              Per_cap_inc="B19301_001", # Per capita income, blk grp
              Aggreg_inc="B19025_001", # Aggregate household income, blk grp
              Med_age="B01002_001") # median age, blk grp

#   All these by tract
acs_vars_t <- c(Pop_tract="B05001_001", # Total population by Tract
              Born_US="B05002_002", # Born in the US, tract
              Born_foreign="B05002_013", # Foreign born, tract
              Not_US_citizen="B05002_021"  # Not a US citizen, tract
              )

age_labels <- c("Total",  "TotM", "M0to5", "M_5to9", "M_10to14", "M_15to17",
 "M_18and19", "M_20", "M_21", "M_22to24", "M_25to29", "M_30to34", "M_35to39",
 "M_40to44", "M_45to49", "M_50to54", "M_55to59", "M_60and61", "M_62to64",
 "M_65and66", "M_67to69", "M_70to74", "M_75to79", "M_80to84", "M_85",
 "TotF", "F0to5", "F_5to9", "F_10to14", "F_15to17", "F_18and19", "F_20", "F_21",
 "F_22to24", "F_25to29", "F_30to34", "F_35to39", "F_40to44", "F_45to49",
 "F_50to54", "F_55to59", "F_60and61", "F_62to64", "F_65and66", "F_67to69",
 "F_70to74", "F_75to79", "F_80to84", "F_85" )

acs_age <- c(paste0("B01001_", sprintf("%03d", 1:49)))

names(acs_age) <- age_labels

```

##    Get the data and save

```{r get data}

Pop <- get_decennial(geography="block",
                     variables=dec_vars,
                     year=2020,
                     state="TX",
                     county="201",
                     output="wide",
                     geometry=TRUE)

ACS_b <- get_acs(geography="block group",
               variables=acs_vars_b,
               year=2020,
               state="TX",
               county="201",
               output="wide",
               geometry=TRUE) 

ACS_t <- get_acs(geography="tract",
               variables=acs_vars_t,
               year=2020,
               state="TX",
               county="201",
               output="wide",
               geometry=TRUE) 

ACS_age <- get_acs(geography="block group",
               variables=acs_age,
               year=2020,
               state="TX",
               county="201",
               output="wide",
               geometry=TRUE) 


path <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Census_data/"

saveRDS(Pop, paste0(path, "Pop_data_by_block_2020.rds"))
saveRDS(ACS_b, paste0(path, "Income_and_Age_by_BlkGrp_2015_2020.rds"))
saveRDS(ACS_t, paste0(path, "Birthplace_citizenship_by_tract_2015-2020.rds"))
saveRDS(ACS_age, paste0(path, "Age_DistributionBySex_by_BlkGrp_2015-2020.rds"))

```

##    Read in HUD crosswalk file and save

Sadly I think the census tracts are for 2010, not 2020, so this is not
helpful.

https://www.huduser.gov/portal/datasets/usps_crosswalk.html#codebook

```{r HUD crosswalk file}

Tract_Xwalk <- readxl::read_excel(paste0(path, "TRACT_ZIP_032020.xlsx"))

Tract_Tx_Xwalk <- Tract_Xwalk %>% 
  filter(stringr::str_detect(TRACT, "^48"))

saveRDS(Tract_Xwalk, paste0(path, "HUD_Crosswalk_file_2010.rds"))
saveRDS(Tract_Tx_Xwalk, paste0(path, "HUD_Crosswalk_Tx_file_2010.rds"))

```

## Calculate crosswalk files for Tracts to zipcodes

I'll do this by first creating a crosswalk table for the blocks based on
overlap area, and using that ratio to weight by population.

```{r block crosswalk table to zip}

folder <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Zipcodes/"
Zips <- readRDS(paste0(folder, "ZCTA_polygons_2020_HoustonArea.rds")) %>% 
  select(ZCTA=ZCTA5CE20)  %>% 
  sf::st_transform(crs=local_crs)  

#   Calculate %area of each block in zipcodes

Test_tracts <- Tract_Tx_Xwalk %>% 
  filter(ZIP=="77008" | ZIP=="77009" | ZIP=="77007")

Test_Pop <- Pop %>% 
  select(GEOID, Pop) %>% 
  #filter(stringr::str_sub(GEOID, end=11) %in% Test_tracts$TRACT) %>% 
  sf::st_transform(crs=local_crs)

Test_out <- sf::st_intersection(Test_Pop, Zips) %>% 
  mutate(area = as.numeric(sf::st_area(geometry))) %>%  # kill off units of m^2
  filter(area>10) # remove boundary issues

Test_out %>% group_by(GEOID) %>% filter(n()>1)

Diffs <- Test_Pop[!(Test_Pop$GEOID %in% Test_out$GEOID),]

leaflet::leaflet() %>% 
  leaflet::addTiles() %>% # OpenStreetMap by default
  leaflet::addPolygons(data=sf::st_transform(Zips,crs=google_crs),
                   color="red",
                   opacity=1,
                   weight=2.5,
                   popup = ~ZCTA,
                   fillOpacity = 0.01) %>% 
  leaflet::addPolygons(data=sf::st_transform(Test_Pop,crs=google_crs), 
                   color="black",
                   opacity=1,
                   weight=0.5,
                   popup = ~GEOID,
                   fillOpacity = 0.01)

#   Add Blk_grp and Tract columns

Test_out <- Test_out %>% 
  mutate(Blk_grp = stringr::str_sub(GEOID, end=12)) %>% 
  mutate(Tract = stringr::str_sub(GEOID, end=11))

#   Create Crosswalk tables for Blk_grp to ZIP and Tract to Zip

Blkgrp_Zip_crosswalk <- Test_out %>% 
  sf::st_drop_geometry() %>% 
  group_by(Blk_grp, ZCTA) %>% 
    summarize(Pop=sum(Pop)) %>% 
  group_by(Blk_grp) %>% 
    mutate(Total_pop=sum(Pop)) %>% 
  ungroup() %>% 
  mutate(ratio=Pop/Total_pop)

Tract_Zip_crosswalk <- Test_out %>% 
  sf::st_drop_geometry() %>% 
  group_by(Tract, ZCTA) %>% 
    summarize(Pop=sum(Pop)) %>% 
  group_by(Tract) %>% 
    mutate(Total_pop=sum(Pop)) %>% 
  ungroup() %>% 
  mutate(ratio=Pop/Total_pop)

leaflet::leaflet() %>% 
  leaflet::addTiles() %>% # OpenStreetMap by default
  leaflet::addPolygons(data=sf::st_transform(Zips,crs=google_crs),
                   color="red",
                   opacity=1,
                   weight=2.5,
                   popup = ~ZCTA,
                   fillOpacity = 0.01) %>% 
  leaflet::addPolygons(data=sf::st_transform(ACS_t,crs=google_crs), 
                   color="black",
                   opacity=1,
                   weight=0.5,
                   popup = ~GEOID,
                   fillOpacity = 0.01)


```



##  push data into zipcodes and save

```{r zipcodes}

#   Read in 2020 ZCTA polygons

#   For tract data I can use the HUD crosswalk file from
#   https://www.huduser.gov/portal/datasets/usps_crosswalk.html#data

ZCTA_Nationality <-  left_join(Tract_Tx_Xwalk, ACS_t, by=c("TRACT"="GEOID"))



a <- tribble(~a, ~b, 1,2,1,3,2,4)
b <- tribble(~a, ~c, 1,5,2,7)

left_join(a,b, by="a")

left_join(b,a, by="a")

```











