---
title: "2023 Census Tract Geometries"
author: "Alan Jackson"
date: "2025-04-25"
format: html
---

##    Download and save the census tract geometries for 2023

```{r}

library(tidyverse)
library(sf)
library(tidycensus)

path <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Census_Tracts_2023"

census_api_key("c458095036ca1037f97b9c7019b6a7ac2dbf90d4")

google_crs <- 4326

```

Grab the geometries and save

```{r}

States <- c("AL", "NY", "AK", "AZ", "AR", "CA", "LA", "CO", "CT", "DE", "DC",
"FL", "GA", "MO", "SC", "HI", "ID", "IL", "IN", "KY", "IA", "KS", "ME", "MD",
"MA", "MI", "MN", "MS", "MT", "NE", "NV", "NH", "NJ", "NM", "NC", "ND", "OH",
"OK", "OR", "PA", "TX", "RI", "SD", "TN", "UT", "VT", "VA", "WA", "WV", "WI",
"WY", "PR")

# state="AL"

for (state in States) {
  
  ACS <- get_acs(geography="tract",
                 variables=c(Pop="B01001_001"),
                 year=2023,
                 state=state,
                 output="wide",
                 geometry=TRUE) 
    
    ACS <- ACS %>% 
      st_transform(crs=google_crs)
  
  saveRDS(ACS, paste0(path, "ACS_2023_", state, ".rds"))
}
  
```




