---
title: "Texas Flood Planning Regions"
author: "Alan Jackson"
format: html
editor: visual
---

## Download data

Data for flood planning region polygons from
https://www.arcgis.com/home/item.html?id=177ba83b8e1a405692ba8886110df08f

Manual download the shapefile

```{r setup, include=FALSE}
library(tidyverse)
library(leaflet)
library(leafem)

googlecrs <- 4326

path <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/FloodPlanningRegions/"

knitr::opts_chunk$set(echo = TRUE)
```


```{r read and write}

fgdb <- paste0(path, "Regional_Flood_Planning_Groups.dbf")

# Read the feature class
temp <- sf::st_read(fgdb)
temp <- sf::st_transform(temp, googlecrs)
# sf::st_crs(temp) <- googlecrs

summary(temp)

leaflet(temp) %>% 
  leaflet::setView(lng = -95.3103, lat = 29.7752, zoom = 8 ) %>%   
  addTiles() %>% 
  addPolygons(weight=1) %>% 
  addStaticLabels(label=temp$RFPG,
                  style = list("color" = "red", "font-weight" = "bold"))


saveRDS(temp, paste0(path, "Regional_Flood_Planning_Groups.Rds"))

map <- leaflet(temp) %>% 
  leaflet::setView(lng = -95.3103, lat = 29.7752, zoom = 8 ) %>%   
  addTiles() %>% 
  addPolygons(weight=1) %>% 
  addStaticLabels(label=temp$RFPG,
                  style = list("color" = "red", "font-weight" = "bold"))

htmlwidgets::saveWidget(map, paste0(path, "test.html"), selfcontained = TRUE)

```