---
title: "HCAD data"
author: "Alan Jackson"
date: "7/6/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

path <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/"



knitr::opts_chunk$set(echo = TRUE)
```

## Harris County Appraisal District

Files read from https://hcad.org/pdata/ for each of the years 2005-2020

Really only want one file out of the zip file, the file real_acct.txt.

These files are large, so I will drop as much data as possible as 
quickly as possible.


```{r read files}

for (year in "2005":"2022") {
  zipfile <- paste0(path, "HCAD/Real_acct_owner_", year,".zip")
  
  df <- readr::read_tsv(unz(description = zipfile, filename = "real_acct.txt"), col_names = TRUE, col_types = strrep("c", 71)) %>% 
    select(acct, yr, state_class, contains("site_addr"), mail_addr_1, 
           bld_ar, land_ar, land_val, bld_val, assessed_val, 
           tot_appr_val, tot_mkt_val, new_own_dt, key_map, Market_Area_1_Dscr,
           yr_impr)
  
  #   Are there rows I can drop? About 100,000!
  
#  df <- df %>% 
#    #   Drop tot_mkt_val = 0. I don't know what that means, but it 
#    #   isn't useful to me.
#    filter(tot_mkt_val>0) %>% 
#    #   Drop site_addr_1 == 0. Don't know what that is, but limited usefulness.
#    filter(site_addr_1!="0") %>% 
#    #   Drop site_addr_2 or site_addr_3 of NA
#    filter(!is.na(site_addr_2), !is.na(site_addr_3))
  
  # These files are really large, so let's store them by year.
  
  print(paste("About to save file for year", year))
  
  # saveRDS(df, paste0(path, "HCAD/Values_", year,".rds"))

}


```

