---
title: "Zipcodes"
author: "Alan Jackson"
date: '2022-04-13'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

path="/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Zipcodes/"

knitr::opts_chunk$set(echo = TRUE)
```

##        Zipcodes

First source is the census bureau

https://www2.census.gov/geo/tiger/TIGER_DP/2019ACS/

filename: ACS_2019_5YR_ZCTA.gdb.zip

```{r census zipcodes}

# lat, long, lat, long
HoustonBounds <- c(30.00, -95.57, 29.60, -95.13)

folder <- paste0("/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Zipcodes/")
filename <- "ACS_2019_5YR_ZCTA.gdb"

censuslayers <- sf::st_layers(paste0(folder, filename))
######################   stopped here. File is really huge.....
layername <- "ACS_2016_5YR_ZCTA"

ZCTApolys <- st_read(paste0(folder, filename), layer = layername) %>%
  select(-c(GEOID10, CLASSFP10, MTFCC10, FUNCSTAT10))

ZCTApolys <- st_transform(ZCTApolys, 4326) # reproject to Google epsg code

#   Map a subset to see how they look
gmap = get_map(location=c(-95.4142, 29.7907), source="google",zoom=10)

HoustonBounds <- c(30.00, -95.57, 29.60, -95.13)
ggmap(gmap, extent='normal', maprange=FALSE, show.legend=FALSE) +
  geom_sf(data=ZCTApolys, mapping=aes(Zip_Code="blue"),fill=NA, inherit.aes=FALSE, show.legend=FALSE) +
  coord_sf(xlim=c(-95.6, -95.2), ylim=c(29.6, 29.9)) 


  saveRDS(ZCTApolys, file = "~/Dropbox/Rprojects/CensusDataframe/ZCTA_polygons_2016.rds")




```

##        Zipcodes 2020

These are the January 1, 2020 zcta polygons from census bureau

https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2020.html#list-tab-ZL70T70JUWQ5OTQD00

https://www.census.gov/cgi-bin/geo/shapefiles/index.php

filename: tl_2020_us_zcta520.zip

```{r census zipcodes 2020}

# lat, long, lat, long
HoustonBounds <- c(ymax=30.30, xmax=-96.20, ymin=29.27, xmin=-94.50)

folder <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Zipcodes/"
filename <- "tl_2020_us_zcta520.shp"

#foo <- rgdal::readOGR(paste0(folder, filename), layer="tl_2020_us_zcta520")


censuslayers <- sf::st_layers(paste0(folder, filename))
layername <- "tl_2020_us_zcta520"

ZCTApolys <- sf::st_read(paste0(folder, filename), layer = layername) %>%
  select(-c(GEOID20, CLASSFP20, MTFCC20, FUNCSTAT20))

ZCTApolys <- sf::st_transform(ZCTApolys, 4326) # reproject to Google epsg code

foo <- sf::st_crop(ZCTApolys, HoustonBounds)

leaflet::leaflet() %>% 
  leaflet::addTiles() %>% # OpenStreetMap by default
  leaflet::addPolygons(data=foo, 
                   color="black",
                   opacity=1,
                   weight=0.5,
                   popup = ~ZCTA5CE20,
                   fillOpacity = 0.01)

  saveRDS(ZCTApolys, paste0(folder, "ZCTA_polygons_2020.rds"))
  saveRDS(foo, paste0(folder, "ZCTA_polygons_2020_HoustonArea.rds"))

```

##        COH zipcode data

Download the shape file from 
https://cohgis-mycity.opendata.arcgis.com/datasets/coh-zipcode/explore?location=29.761150%2C-95.394800%2C9.16

filename: COH_ZIPCODE.zip

```{r City data}

#   Read in the shapefiles

Zip_polys <- sf::read_sf(paste0(path,"COH_ZIPCODE.shp"))

summary(Zip_polys)

#   CRS is good, we have polys, I think I'm happy. Let's plot them

plot(Zip_polys)

saveRDS(Zip_polys, paste0(path, "COH_Zip_Polys.rds"))


```

