---
title: "Texas County Boundaries"
author: "Alan Jackson"
date: "6/27/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)


path <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Texas_Counties/"

knitr::opts_chunk$set(echo = TRUE)
```

##    Read in county files

Read in two file, the county file by csv for building a table of standard
county names and FIP code correspondence, and also then read in the shapefile
for actually drawing county outlines on a map.

```{r read CSV}

Counties <- read_csv(paste0(path, "Texas_County_Boundaries.csv")) %>% 
  select(-SHAPE_Length, -SHAPE_Area)

# The state has problems spelling this correctly

Counties$CNTY_NM[Counties$CNTY_NM=="De Witt"] <- "DeWitt"

# Make FIPS code character and remove state code

Counties$FIPS_ST_CNTY_CD <- as.character(Counties$FIPS_ST_CNTY_CD)
Counties$FIPS_ST_CNTY_CD <- str_remove(Counties$FIPS_ST_CNTY_CD, "^48")

# Save file out

saveRDS(Counties, paste0(path, "County_Names.rds"))

```

##        Read in the shapefile

```{r read shapefile}

County_outlines <- sf::st_read(paste0(path, "County.shp"))

# The state has problems spelling this correctly

County_outlines$CNTY_NM[Counties$CNTY_NM=="De Witt"] <- "DeWitt"

County_outlines <- County_outlines %>% 
  sf::st_as_sf()  

saveRDS(County_outlines, paste0(path, "County_Outlines.rds"))

```

